### ISSUE TITLE
為何要封鎖 google.com？

### ISSUE THREAD

**Issue by danny0838** [scyrte/uBlacklist-Subscription#3]
如題，真的不是有什麼誤會嗎？XD

**Comment by scyrte** [comment]
`# 自用规则，纯人工收集记录，除垃圾网站外，也包含正常网站，比如：*://*.z.baidu.com/*，请注意`

可自行添加白名单

**Comment by danny0838** [comment]
這我瞭解，只是想知道名單中的 `*://*.google.com/*` 規則是否為誤植？如果不是誤植，我想瞭解本黑名單的標準是怎麼設定的，這樣比較清楚該如何使用它。

**Comment by Delta-in-hub** [comment]
搜gmail没搜到，才来看规则，人麻了。
